---
name: idr0146-dominguez-heartlightsheet/experimentA
version: 1

defaults:
  # Should the column be processed when creating bulk-annotations (yes/no)
  include: no
  # Columns type of the bulk-annotations column
  type: string

  # If non-empty a string used to separate multiple fields in a column
  # White space will be stripped
  split: ;
  # Should this column be included in the clients (yes/no)
  includeclient: yes
  # Should this column be visible in the clients, if no the column should be
  # hidden in the client but will still be indexed by the searcher (yes/no)
  visible: yes
  # Should empty values be omitted from the client display
  omitempty: yes

columns:

  - name: Characteristics [Strain]
    clientname: Strain
    include: yes
  - name: Reporter
    clientname: Reporter
    include: yes
  - name: Experimental Condition [Genotype]
    clientname: Genotype
    include: yes
  - name: Comment [Genotype Comments]
    clientname: Genotype Comments
    include: yes
  - name: Characteristics [Developmental Stage]
    clientname: Developmental Stage
    include: yes
  - name: Comment [Developmental Stage]
    clientname: Developmental Stage Description
    include: yes
  - name: Material Type
    clientname: Material Type
    include: yes
  - name: Characteristics [Growth Condition]
    clientname: Growth Condition
    include: yes

  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: yes

advanced:
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
